"""
core/message.py — defines what a message looks like and the vocabulary of
"performatives" (speech acts) that agents use to talk to each other.

WHY PERFORMATIVES?
  In a Multi-Agent System (MAS), agents do not call each other's functions
  directly.  Instead they exchange messages that carry intent.  The performative
  field says WHY a message is being sent (a request, an agreement, a result…)
  rather than HOW to act on it.  This mirrors the FIPA-ACL standard used in
  academic MAS research and satisfies the CNP (Contract Net Protocol) requirement.
"""

import uuid   # generates unique IDs so every message can be traced
import time   # records when a message was created
from dataclasses import dataclass, field   # clean, auto-generated __init__ and __repr__
from typing import Any, Dict, Optional


# ---------------------------------------------------------------------------
# Performative vocabulary
# ---------------------------------------------------------------------------

class Performative:
    """
    Named constants for the 'why' of a message — its speech-act type.

    The system uses a subset of FIPA-ACL performatives:

      REQUEST  — "Please do this for me."
                  e.g. PartAgent asks CraneAgent to execute a route.

      AGREE    — "OK, I accept your request and will start working on it."
                  e.g. CraneAgent tells PartAgent it has received the route.

      INFORM   — "Here is the result / status update."
                  e.g. CraneAgent tells PartAgent the route is complete.

      FAILURE  — "I tried but could not do what you asked."
                  e.g. CraneAgent tells PartAgent the route failed (station broke).

      CFP      — Call For Proposal.  Not heavily used here but part of the standard
                  Contract Net Protocol where a manager broadcasts a job to workers.

      PROPOSE  — A worker's bid in response to a CFP.

      ACCEPT / REJECT — Manager accepts or rejects a bid.

      REFUSE   — Agent refuses to even attempt the request
                  (different from FAILURE which means it tried and could not finish).
    """
    CFP     = "CFP"
    PROPOSE = "PROPOSE"
    ACCEPT  = "ACCEPT"
    REJECT  = "REJECT"
    INFORM  = "INFORM"
    FAILURE = "FAILURE"
    REQUEST = "REQUEST"
    AGREE   = "AGREE"
    REFUSE  = "REFUSE"


# ---------------------------------------------------------------------------
# Message dataclass
# ---------------------------------------------------------------------------

@dataclass  # Python auto-generates __init__, __repr__, __eq__ from the fields below
class Message:
    """
    A single unit of inter-agent communication.

    Fields
    ------
    performative : str
        The speech-act type (one of the Performative constants above).
        Tells the receiver HOW to interpret the message.

    sender : str
        The agent_id of whoever sent this message.

    receiver : str
        The agent_id of the intended recipient.
        The MessageBus uses this to route the message to the right mailbox.

    content : dict
        The payload — a free-form dict whose keys depend on the performative.
        Example for a REQUEST:  {"action": "execute_route", "route": [...]}
        Example for an INFORM:  {"action": "route_done",   "part_id": "Part_Source1_1"}

    msg_id : str
        A universally-unique identifier auto-generated by uuid4().
        Useful for debugging ("which message caused this?").

    reply_to : str | None
        If this message is a reply, this field stores the msg_id of the original.
        Lets you trace a full request→agree→inform chain.

    timestamp : float
        Unix time (seconds since epoch) when the message was created.
        Auto-filled by time.time().
    """

    performative: str                                         # required — speech act
    sender:       str                                         # required — who sent it
    receiver:     str                                         # required — who receives it
    content:      Dict[str, Any]                              # required — the payload

    # These three have defaults, so they are optional at construction time:
    msg_id:    str            = field(default_factory=lambda: str(uuid.uuid4()))
    reply_to:  Optional[str] = field(default=None)
    timestamp: float          = field(default_factory=time.time)

    def create_reply(self, performative: str, sender: str,
                     content: Dict[str, Any]) -> "Message":
        """
        Convenience method: build a reply to THIS message.

        The new message's receiver is automatically set to the original sender,
        and reply_to is set to this message's msg_id — preserving the conversation chain.

        Usage:
            agree = request_msg.create_reply(Performative.AGREE, self.agent_id,
                                             {"status": "ok"})
            self.send(agree)
        """
        return Message(
            performative=performative,
            sender=sender,
            receiver=self.sender,   # flip: reply goes back to whoever sent the original
            content=content,
            reply_to=self.msg_id,   # links this reply to the original message
        )
